// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa1bo_eeg8dn9LKulKsj8-7d_nrDV9Lbc',
    appId: '1:311013004660:web:f5b535ab205f0385338821',
    messagingSenderId: '311013004660',
    projectId: 'lost-found-app-2026',
    authDomain: 'lost-found-app-2026.firebaseapp.com',
    storageBucket: 'lost-found-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ_7aXn3Bcl1UrwcnQpnVfl1t3HP2vDG4',
    appId: '1:311013004660:android:0e9d613babcd4063338821',
    messagingSenderId: '311013004660',
    projectId: 'lost-found-app-2026',
    storageBucket: 'lost-found-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGfdogsWFAitcUwzAppmfcG32nbaW6_sw',
    appId: '1:311013004660:ios:806df13e3988d422338821',
    messagingSenderId: '311013004660',
    projectId: 'lost-found-app-2026',
    storageBucket: 'lost-found-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGfdogsWFAitcUwzAppmfcG32nbaW6_sw',
    appId: '1:311013004660:ios:806df13e3988d422338821',
    messagingSenderId: '311013004660',
    projectId: 'lost-found-app-2026',
    storageBucket: 'lost-found-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.lostFoundApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa1bo_eeg8dn9LKulKsj8-7d_nrDV9Lbc',
    appId: '1:311013004660:web:16765a955685beb4338821',
    messagingSenderId: '311013004660',
    projectId: 'lost-found-app-2026',
    authDomain: 'lost-found-app-2026.firebaseapp.com',
    storageBucket: 'lost-found-app-2026.firebasestorage.app',
  );
}
